# Generated by Django 5.1.7 on 2025-03-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DialectWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10, verbose_name="编号")),
                ("word", models.CharField(max_length=50, verbose_name="词汇")),
                (
                    "old_dialect_word",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="老派词汇"
                    ),
                ),
                (
                    "old_dialect_audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="old_dialect/",
                        verbose_name="老派语音",
                    ),
                ),
                (
                    "new_dialect_word",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="新派词汇"
                    ),
                ),
                (
                    "new_dialect_audio",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="new_dialect/",
                        verbose_name="新派语音",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "方言词汇",
                "verbose_name_plural": "方言词汇",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="core_dialec_code_8733a7_idx"),
                    models.Index(fields=["word"], name="core_dialec_word_8c1253_idx"),
                    models.Index(
                        fields=["old_dialect_word"],
                        name="core_dialec_old_dia_264975_idx",
                    ),
                    models.Index(
                        fields=["new_dialect_word"],
                        name="core_dialec_new_dia_da5b35_idx",
                    ),
                ],
            },
        ),
    ]
